name: dart_srp
description: JAVA SRP NIMBUS port in dart.
homepage: https://infotamia.com
version: 1.0.3
repository: https://github.com/MoeAl-Ani/dart_srp
license: MIT

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.6.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
