name: dart_srp
description: JAVA SRP NIMBUS port in dart.
version: 1.0.1
repository: https://github.com/MoeAl-Ani/dart_srp

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.6.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
